### PR TITLE
fix: CoreData apply default retention policy to none autoEvent

### LINKED ISSUE #5188: Allow default retention policy can apply to events not coming from auto events
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: Core Data

### Is this a regression?

 NO

### Description and Minimal Reproduction [**REQUIRED**]
The current default retention policy will only apply to events coming from auto events, which causes those events not coming from auto events remain in the database. Some device services, such as device-rest and device-websocket, don’t have the concept of auto events, so we should allow default retention policy can apply to these events.

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version [**REQUIRED**]:**

**Anything else relevant?**

### PR DESCRIPTION
**Pull request by weichou1229**
CoreData apply default retention policy to events not coming from auto events

Close #5188

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [x] I have added unit tests for the new feature or bug fix (if not, why?)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions

Deploy core service and device-virtual to test the event purge.

### CODE REVIEW

File: internal/core/data/application/reading.go [hunk 1]
```diff
@@ -465,3 +471,54 @@ func countBasedEventRetention(deviceName string, autoEvent models.AutoEvent, dic
...
+// noneAutoEventSourcesByDevice returns sources that are not defined in the device's auto events
+func noneAutoEventSourcesByDevice(device models.Device, dic *di.Container) ([]string, errors.EdgeX) {
+	profileClient := bootstrapContainer.DeviceProfileClientFrom(dic.Get)
+	profile, err := profileClient.DeviceProfileByName(context.Background(), device.ProfileName)
+	if err != nil {
+		return nil, errors.NewCommonEdgeX(errors.Kind(err), fmt.Sprintf("retrieve event sources not in auto events from the device '%s'", device.Name), err)
+	}
+	var sources []string
+	for _, r := range profile.Profile.DeviceResources {
+		if contained := slices.ContainsFunc(device.AutoEvents, func(event models.AutoEvent) bool {
```
Comment (judehung) [inline internal/core/data/application/reading.go:502]:
```suggestion
                // skip the device resource that is associated with any AutoEvent definitions.
		if contained := slices.ContainsFunc(device.AutoEvents, func(event models.AutoEvent) bool {
```

File: internal/core/data/application/reading.go [hunk 2]
```diff
@@ -465,3 +471,54 @@ func countBasedEventRetention(deviceName string, autoEvent models.AutoEvent, dic
...
+			return event.SourceName == r.Name
+		}); contained {
+			continue
+		}
+		if r.Properties.ReadWrite == common.ReadWrite_W {
```
Comment (judehung) [inline internal/core/data/application/reading.go:507]: Please add comment to explain why skip resources with ReadWrite_W

File: internal/core/data/application/reading.go [hunk 3]
```diff
@@ -465,3 +471,54 @@ func countBasedEventRetention(deviceName string, autoEvent models.AutoEvent, dic
...
+		}
+		sources = append(sources, r.Name)
+	}
+	for _, c := range profile.Profile.DeviceCommands {
+		if contained := slices.ContainsFunc(device.AutoEvents, func(event models.AutoEvent) bool {
+			return event.SourceName == c.Name
+		}); contained {
+			continue
+		}
+		if c.ReadWrite == common.ReadWrite_W {
```
Comment (judehung) [inline internal/core/data/application/reading.go:518]: Please add comment to explain why skip device command with ReadWrite_W

File: internal/core/data/application/reading.go [hunk 4]
```diff
@@ -314,8 +316,8 @@ func AsyncPurgeEvent(ctx context.Context, dic *di.Container) errors.EdgeX {
 					err = purgeEventByAutoEvents(dic)
 					if err != nil {
 						lc.Errorf("Failed to purge events and readings, %v", err)
-						break
 					}
+					continue
```
[the remark this answers is not in the document]
Comment (weichou1229) [reply internal/core/data/application/reading.go]: Reverted

File: internal/core/data/application/reading.go (hunk 3 above)
Comment (weichou1229) [reply internal/core/data/application/reading.go:522]: Added the comment.

File: internal/core/data/application/reading.go [hunk 5]
```diff
@@ -465,3 +471,54 @@ func countBasedEventRetention(deviceName string, autoEvent models.AutoEvent, dic
...
+		}); contained {
+			continue
+		}
+		if r.Properties.ReadWrite == common.ReadWrite_W {
+			continue
+		}
+		sources = append(sources, r.Name)
+	}
+	for _, c := range profile.Profile.DeviceCommands {
+		if contained := slices.ContainsFunc(device.AutoEvents, func(event models.AutoEvent) bool {
```
[the remark this answers is not in the document]
Comment (weichou1229) [reply internal/core/data/application/reading.go:516]: Added the comment.

**Review by judehung — APPROVED** [review]
LGTM
