### PR TITLE
fix: Created timestamp is 0 on message queue

### LINKED ISSUE #2602: created timestamp always 0
# 🐞 Bug Report

### Affected Services
Core Data

### Is this a regression?
Worked in Edinburgh but not Fuji and later

### Description and Minimal Reproduction
The created timestamp on event/reading is 0.  The created timestamp does get set in the database, but it is not set back into the event/reading and when the event/reading is pushed to app services (via 0MQ or message bus), the created timestamp is always zero.

in a nutshell -- Event param to AddEvent the event is not a pointer (https://github.com/edgexfoundry/edgex-go/blob/ad8ce46ea1b4c1cfb589e4a1128cf4f50d0a06e9/internal/pkg/db/mongo/data.go#L51)
the created and modified are being set here in this call just before save to DB but the call to put it on the bus happens after this call returns -- using the same event that was passed in -- which wont have those fields populated

## 🔥 Exception or Error
no exception or error - just no created timestamp

## 🌍  Your Environment
works the same for all environments

**EdgeX Version:**
Fuji or later

**Anything else relevant?**
See #core slack channel exchange around June 25 for exchange between bug finder and Lenny/Rocky

### PR DESCRIPTION
**Pull request by lindseysimple**
Fix by using the db creation time on message queue for Event.
closes #2602

Signed-off-by: Lindsey Cheng <beckysocute@gmail.com>

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit subject follows the [Conventional Commits spec](https://github.com/zeke/semantic-pull-requests)
- [x] The commit message follows the [EdgeX Contributor Guide](https://wiki.edgexfoundry.org/display/FA/Contributor%27s+Guide)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [x] `make test` has completed successfully

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

The created timestamp of Event/Reading is zero on the message queue (can be seen on the app services pushed via 0MQ or message bus).
Issue Number: #2602 

## What is the new behavior?
The created timestamp of Event/Reading value should be the same as the created field saved in the database on the message queue, which is the entry creation timestamp in the database.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Are there any new imports or modules? If so, what are they used for and why?
No.

### CODE REVIEW

File: internal/core/data/event.go [hunk 1]
```diff
@@ -139,6 +139,10 @@ func addNewEvent(
 			return "", err
 		}
 		e.ID = id
+		savedEvent, err := dbClient.EventById(id)
```
Comment (lenny-intel) [inline internal/core/data/event.go:142]: Would it be better to simply set `created` prior to calling AddEvent so we don't have to make a call to read back the Event from the DB?

Comment (rsdmike) [reply internal/core/data/event.go:142]: Alternatively, why don't we have AddEvent return the event it inserted? That's more standard isn't it?

Comment (lindseysimple) [reply internal/core/data/event.go]: @lenny-intel, updated the fix based on your suggestion to set the `created` timestamp before calling the `dbClient.AddEvent` function.

@rsdmike , the suggestion sounds great and we'll implement in the v2 API changes. Currently the change is included in https://github.com/edgexfoundry/edgex-go/pull/2610.

File: internal/core/data/event.go [hunk 2]
```diff
@@ -134,6 +134,9 @@ func addNewEvent(
 
 	// Add the event and readings to the database
 	if configuration.Writable.PersistData {
+		if e.Created == 0 {
+			e.Created = db.MakeTimestamp()
```
Comment (lenny-intel) [inline internal/core/data/event.go:138]: Also need to remove setting it in the DB layer for Redis (so saved value is the value set here). Mongo code is going to be removed, so you can ignore it.

**Comment by lindseysimple** [comment]
@lenny-intel Hi Lenny, I've removed the `created` value check in `addEvent` function of db layer, could you please re-review that? Thanks for your help.
