### PR TITLE
PUT or POST interval action not work

### LINKED ISSUE #1497: PUT or POST interval action not work
I don't know how to create POST or PUT interval action and didn't found any clue in the source code.
The http request body is nil and params only use for ContentLengthKey
```
	req, err := http.NewRequest(httpMethod, executingUrl, nil)
	req.Header.Set(ContentTypeKey, ContentTypeJsonValue)

	params := strings.TrimSpace(intervalAction.Parameters)

	if len(params) > 0 {
			req.Header.Set(ContentLengthKey, string(len(params)))
	}
```
https://github.com/edgexfoundry/edgex-go/blob/master/internal/support/scheduler/schedule.go#L465

### Affected Services
support-scheduler

### Is this a regression?
I not sure.  I didn't found any description to setup a POST or PUT action.
https://docs.edgexfoundry.org/Ch-APISupportingServicesScheduling.html

## 🌍  Your Environment
**Deployment Environment:**
macos
**EdgeX Version:**
edgex-go master branch

### PR DESCRIPTION
**Pull request by xmlviking**
Fix #1497

Added code to enable parameters to be included as body for POST and PUT
httpMethods.

Updated Scheduler.RST documentation to reflect the changes in types from Schedule, ScheduleEvent to Interval, IntervalAction. 

Signed-off-by: xmlviking <ecotter@gmail.com>

### CODE REVIEW

File: internal/support/scheduler/schedule.go [hunk 1]
```diff
@@ -498,6 +490,29 @@ func execute(context *IntervalContext, wg *sync.WaitGroup) error {
 	return nil
 }
 
+// EFC We may need to modify this for authorization type in the future
+func getRequestMethod(httpMethod string, executingUrl string, intervalAction contract.IntervalAction) (*http.Request, error) {
```
Comment (weichou1229) [inline internal/support/scheduler/schedule.go]: @xmlviking I tested on my local machine and work fine.
Why not use `getHttpRequest` instead of the `getRequestMethod`?

File: docs/api/Ch-APISupportingServicesScheduling.rst [hunk 2]
```diff
@@ -26,93 +26,76 @@ https://github.com/edgexfoundry/edgex-go/blob/master/api/raml/support-scheduling
...
+    "target": "core-data",
+    "protocol": "http",
+    "httpMethod": "DELETE",
+    "address": "localhost",
+    "port": 48080,
+    "path": "/api/v1/event/scrub"}' "http://localhost:48085/api/v1/intervalaction"
 
-For testing update the midnight service to be every 60 seconds
 
+An Interval Action which connects to edgex-device-modbus every 20 seconds and updates a random flag. Using the every20s interval
```
Comment (weichou1229) [inline docs/api/Ch-APISupportingServicesScheduling.rst]: This is Random-Boolean-Device which created by edgex-device-virtual.

**Comment by xmlviking** [comment]
recheck

**Comment by tsconn23** [comment]
@xmlviking Be advised that docs are being deleted with this PR https://github.com/edgexfoundry/edgex-go/pull/1562

The content in this PR should be moved to the new egdex-docs repo

**Comment by tsconn23** [comment]
recheck

**Comment by xmlviking** [comment]
The docs have been moved into the edges-docs as well

**Comment by tsconn23** [comment]
@xmlviking You'll need to address the conflict

**Comment by xmlviking** [comment]
Will do ty

**Comment by xmlviking** [comment]
recheck

**Comment by xmlviking** [comment]
recheck
