### PR TITLE
fix issue #1651: fixed typo for insecureskipverify; set the default value as false

### LINKED ISSUE #1651: Fix typo in option name pertaining to verifying HTTPS hosts
Reported by @anonymouse64 in the context of https://github.com/edgexfoundry/edgex-go/pull/1627
The option name for not verifying HTTPS hosts has a typo in it in  
cmd/security-proxy-setup/main.go:

flag.BoolVar(&ensureSkipVerify, "insureskipverify"

### PR DESCRIPTION
**Pull request by tingyuz**
Fix #1651 

correct the typo for insecureskipverify in the security-proxy-setup project, and set the default value as false.

Signed-off-by: Tingyu Zeng <tingyu.zeng@rsa.com>

### CODE REVIEW

File: cmd/security-proxy-setup/main.go [hunk 1]
```diff
@@ -34,15 +34,15 @@ func main() {
...
+	var insecureskipverify bool
 	var resetNeeded bool
 	var useProfile string
 	var userTobeCreated string
 	var userOfGroup string
 	var userToBeDeleted string
 	var useRegistry bool
 
-	flag.BoolVar(&ensureSkipVerify, "insureskipverify", true, "skip server side SSL verification, mainly for self-signed cert")
+	flag.BoolVar(&insecureskipverify, "insureskipverify", false, "skip server side SSL verification, mainly for self-signed cert")
```
Comment (anonymouse64) [inline cmd/security-proxy-setup/main.go]: this is still a typo

also not camel case like for security-secretstore-setup where it is `insecureSkipVerify`

File: internal/pkg/usage/usage.go [hunk 2]
```diff
@@ -55,7 +55,7 @@ Usage: %s [options]
 Server Options:	
     -p, --profile <name>            Indicate configuration profile other than default
     -r, --registry                  Indicates service should use Registry
-	--insureskipverify=true/false   Indicates if skipping the server side SSL cert verifcation, similar to -k of curl
+	--insecureskipverify=true/false   Indicates if skipping the server side SSL cert verification, similar to -k of curl
```
Comment (anonymouse64) [inline internal/pkg/usage/usage.go]: should be camel case see other comment

File: cmd/security-proxy-setup/main.go (hunk 1 above)
Comment (tingyuz) [reply cmd/security-proxy-setup/main.go]: fixed.

File: internal/pkg/usage/usage.go (hunk 2 above)
Comment (tingyuz) [reply internal/pkg/usage/usage.go]: Fixed.

Comment (tingyuz) [reply internal/pkg/usage/usage.go]: Fixed.

File: cmd/security-proxy-setup/main.go (hunk 1 above)
Comment (tingyuz) [reply cmd/security-proxy-setup/main.go]: Fixed.

File: internal/pkg/usage/usage.go (hunk 2 above)
Comment (tingyuz) [reply internal/pkg/usage/usage.go]: Fixed.

**Comment by tsconn23** [comment]
recheck

File: cmd/security-proxy-setup/main.go (hunk 1 above)
Comment (tingyuz) [reply cmd/security-proxy-setup/main.go]: Fixed.

File: internal/pkg/usage/usage.go (hunk 2 above)
Comment (tingyuz) [reply internal/pkg/usage/usage.go]: Fixed.
