### PR TITLE
The new boot functionality immediate creates a startup parameter with…

### LINKED ISSUE #1886: StartupTimer expects wait in seconds, getting milliseconds
# 🐞 Bug Report

### Affected Services

 The issue is located in: 
New method of bootstrapping the services which use the newly-created StartupTimer

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
Yes because previously - before the recent bootstrap changes - the milliseconds was acted upon correctly.  No, because this is new functionality.  :)

### Description and Minimal Reproduction
The method startup.NewStartupTimer which creates the startup timer takes two parameters: retryIntervalInSeconds and maxWaitInSeconds.  The interval is hard-coded as '1' as there's no constant for it.

However, internal.BootTimeoutDefault is 30000, which is milliseconds and is what was correctly used in the previous implementation.  However, it's also used when creating the startup timer which, in fact, is defining the boot timeout as 30,000 seconds, not 30 seconds as I believe is expected. 

## 🔥 Exception or Error
There's no exception or error that's going to occur; just that it's going to take 8 1/3 hours for the service to timeout if the boot does not successfully complete.
<pre><code>

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version:**

**Anything else relevant?**
The change is simple: create a new constant that is number of seconds and not milliseconds.  For completeness, create a constant for the retry interval

### PR DESCRIPTION
**Pull request by scsosna99**
… the parameters '1' and 'internal.BootTimeoutDefault'

BootTimeoutDefault is from the original implementation, in milliseconds, but startup.NewStartupTimer expects seconds.  To fix without breaking the existing usages of internal.BootTimeoutDefault, created a BootTimeoutSecondsDefault and changed all instances of NewStartupTimer to use that.

I also added a BootRetrySecondsDefault for completeness and add it to the calls creating the new startup timer.

Fix #1886

Signed-off-by: Scott C Sosna <me@scottsosna.dev>

### CODE REVIEW

File: internal/constants.go [hunk 1]
```diff
@@ -15,6 +15,8 @@ package internal
 
 const (
 	BootTimeoutDefault             = 30000
+	BootTimeoutSecondsDefault      = 30
```
Comment (michaelestrin) [inline internal/constants.go]: BootTimeoutSecondsDefault = BootTimeoutDefault/1000

Comment (scsosna99) [reply internal/constants.go]: The reason I didn't do that is because very soon BootTimeoutDefault will no longer be used and therefore can just be deleted....probably could be made a separate issue to do the cleanup as dependencies on the 2 or 3 remaining usages.

Comment (scsosna99) [reply internal/constants.go]: Little confused by comment about needing to multiply by seconds, looks like it's already there.
`func NewStartUpTimer(retryIntervalInSeconds, maxWaitInSeconds int) Timer {
	return Timer{
		startTime: time.Now(),
		duration:  time.Millisecond * time.Duration(maxWaitInSeconds),
		interval:  time.Millisecond * time.Duration(retryIntervalInSeconds),
	}
}
`

Comment (scsosna99) [reply internal/constants.go]: so Internally StartupTimer changes the duration and interval to milliseconds so that comparisons to milliseconds the rest of the way works.

Comment (michaelestrin) [reply internal/constants.go]: > The reason I didn't do that is because very soon BootTimeoutDefault will no longer be used and therefore can just be deleted....probably could be made a separate issue to do the cleanup as dependencies on the 2 or 3 remaining usages.

These two constants are the same constant expressed in different units of measure -- one is in seconds and the other in milliseconds.  Explicitly tie them together and leave it to a follow-on PR to set BootTimeoutSecondsDefault to 30 when BootTimeoutDefault has all other references removed from the code.

Comment (michaelestrin) [reply internal/constants.go]: > Little confused by comment about needing to multiply by seconds, looks like it's already there.

It isn't.  The code is multiplying by `time.Millisecond` and not by `time.Second` which is why the code actually does timeout after 30 seconds (and not the 30,000 seconds as you reported). Even though the variable name denotes unit-of-measure as seconds, we're passing in milliseconds (and multiplying that value by time.Millisecond to get the common duration in nanoseconds.

Run master core data as described above without any changes and verify that it times out after 30 seconds.  Then run it again with the changes in this PR to verify it times out immediately.

**Comment by michaelestrin** [comment]
LGTM pending successful build.
