### PR TITLE
Standardize error usage

### LINKED ISSUE #1671: Standardize Error Types to NOT Use Pointers
We have a number of custom error types in EdgeX such as those found here

- [core-data](https://github.com/edgexfoundry/edgex-go/blob/master/internal/core/data/errors/types.go)
- [core-metadata](https://github.com/edgexfoundry/edgex-go/blob/master/internal/core/metadata/errors/types.go)

Older exception types are defined in a manner where their `New()` functions [return a pointer](https://github.com/edgexfoundry/edgex-go/blob/7ef8bff0a329065968754ab0ab9affabe0155e66/internal/core/data/errors/types.go#L104)

Over time, new exception types have been added wherein the `New()` function [does not](https://github.com/edgexfoundry/edgex-go/blob/7ef8bff0a329065968754ab0ab9affabe0155e66/internal/core/metadata/errors/types.go#L119) return a pointer.

We need to ensure universal implementation on this and right now, I'm of the opinion that these error types do not need to be returned from their `New()` functions as pointers. They're small, don't have any pointers as members and we want them to be immutable.

Along with reconciling these definitions, switch statements used for type checking should no longer expect pointers. Example of current code:

```
switch err.(type) {
		case *types.ErrDuplicateName:
			http.Error(w, err.Error(), http.StatusConflict)
		case *types.ErrItemNotFound:
			http.Error(w, err.Error(), http.StatusNotFound)
		default:
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
```
The pointer dereference will need to be removed from all such statements.

### PR DESCRIPTION
**Pull request by AnthonyMBonafide**
Fix #1671

Update constructors, error type checks, and tests to use values rather
than references(pointers) for errors.

Update tests to conform to the changes in the production code.

Signed-off-by: Anthony M. Bonafide <AnthonyMBonafide@gmail.com>

### CODE REVIEW

File: internal/core/data/operators/value_descriptor/get_test.go [hunk 1]
```diff
@@ -95,7 +95,7 @@ func TestGetValueDescriptorsByNames(t *testing.T) {
 			config.ServiceInfo{MaxResultCount: 1},
 			nil,
 			true,
-			&errors2.ErrLimitExceeded{},
```
Comment (brandonforster) [inline internal/core/data/operators/value_descriptor/get_test.go]: While we're in the neighborhood, should we update this from `errors2`?

File: internal/core/metadata/rest_deviceprofile.go [hunk 2]
```diff
@@ -110,7 +110,7 @@ func restUpdateDeviceProfile(w http.ResponseWriter, r *http.Request) {
 				http.Error(w, err.Error(), err.(types.ErrServiceClient).StatusCode)
 			case errors.ErrDeviceProfileNotFound:
 				http.Error(w, err.Error(), http.StatusNotFound)
-			case *errors2.ErrValueDescriptorsInUse:
+			case errors2.ErrValueDescriptorsInUse:
```
Comment (brandonforster) [inline internal/core/metadata/rest_deviceprofile.go]: Another `errors2`.

File: internal/core/data/operators/value_descriptor/get_test.go [hunk 3]
```diff
@@ -167,7 +167,7 @@ func TestGetAllValueDescriptors(t *testing.T) {
...
+			errors2.ErrLimitExceeded{},
```
Comment (brandonforster) [inline internal/core/data/operators/value_descriptor/get_test.go]: Another `errors2`.

File: internal/core/data/operators/reading/get_test.go [hunk 4]
```diff
@@ -120,7 +120,7 @@ func TestGetReadingsExecutor(t *testing.T) {
 			config.ServiceInfo{MaxResultCount: 1},
 			nil,
 			true,
-			&errors2.ErrLimitExceeded{},
+			errors2.ErrLimitExceeded{},
```
Comment (brandonforster) [inline internal/core/data/operators/reading/get_test.go]: Another `errors2`.

**Comment by AnthonyMBonafide** [comment]
I verified these changes with the black-box tests. Everything seems to be good. However, there were some test failures, but they also existed in the `master` branch. After closer inspection of the test failures I was seeing, none of them were due to these changes. I did not determine why some were failing, I chalked it up to something being wrong with my setup as I had to re-work a few things as most of them were related to state. If I notice anything I will create an issue.

**Comment by AnthonyMBonafide** [comment]
The SonarCloud quality gate is failing due to duplicate code. It is highlighting the code that I changed. The code in question is not new just a change to avoid using pointers. The duplicate code issue is expected to be handled in the Error handling re-work issue #1734 .

File: internal/core/data/operators/value_descriptor/get_test.go (hunk 1 above)
Comment (AnthonyMBonafide) [reply internal/core/data/operators/value_descriptor/get_test.go]: Good point, I think I will follow what you have done recently and alias the `builtin/errors` with `goErrors` and remove the alias from our errors.

**Comment by tsconn23** [comment]
> The SonarCloud quality gate is failing due to duplicate code. It is highlighting the code that I changed. The code in question is not new just a change to avoid using pointers. The duplicate code issue is expected to be handled in the Error handling re-work issue #1734 .

Agreed, this code is pre-existing and SonarQube is treating it as new code based on the inclusion in this PR. What's also interesting is that it's penalizing duplicates not just in a single file but in files across applications (like router.go in both export-client and export-distro). It could be instructive to look at this report and refactor where it makes sense, but that's out of scope for what we're doing here and can be handled via other issues/PRs IMHO.

We also need to take a look at how to get around this `errors` aliasing. Perhaps the package for our custom errors should be unique -- like `internal/pkg/types/errors.go`. That way `types` doesn't conflict with `errors`. And when it conflicts with `types` from `go-mod-core-contracts`, I'd be more comfortable with a descriptive `contractTypes` alias.
