### PR TITLE
Fix: Delayed start services for support- services fail

### LINKED ISSUE #4152: Delayed start support services failed
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: security-spiffe-token-provider

### Is this a regression?
No

### Description and Minimal Reproduction [**REQUIRED**]
Run support services with delayed-started configuration

## 🔥 Exception or Error

It seems like the service-key(`support-notifications`) sending to `/api/v2/gettoken` API  
is not identical to service-name(`notifications`) parsed from SVID

<pre><code>
support services:
level=INFO ts=2022-09-13T08:21:40.628715463Z app=support-notifications source=secret.go:165 msg="runtime token provider enabled"
level=INFO ts=2022-09-13T08:21:40.628728253Z app=support-notifications source=methods.go:138 msg="using Unix Domain Socket at unix:///tmp/edgex/secrets/spiffe/public/api.sock"
level=INFO ts=2022-09-13T08:21:40.728993534Z app=support-notifications source=methods.go:150 msg="workload got X509 source"
level=WARN ts=2022-09-13T08:21:40.757491841Z app=support-notifications source=secret.go:111 msg="Retryable failure while creating SecretClient: failed to get spiffe-token-provider gettoken api call, status code = 400 "

security-spiffe-token-provider:
...
level=DEBUG ts=2022-09-13T08:22:34.172212307Z app=security-spiffe-token-provider source=init.go:165 msg="receiving gettoken request"
level=DEBUG ts=2022-09-13T08:22:34.172257441Z app=security-spiffe-token-provider source=init.go:191 msg="extracting peer SVID from TLS peer certificates..."
level=DEBUG ts=2022-09-13T08:22:34.172266177Z app=security-spiffe-token-provider source=init.go:206 msg="verifying SVID format and server key..."
level=ERROR ts=2022-09-13T08:22:34.172444993Z app=security-spiffe-token-provider source=init.go:249 msg="SK: support-notifications, SN: notifications"
level=ERROR ts=2022-09-13T08:22:34.172451588Z app=security-spiffe-token-provider source=init.go:250 msg="unequal service key and servie name fo

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**
Ubuntu

**EdgeX Version [**REQUIRED**]:**
latest dev images

**Anything else relevant?**

### PR DESCRIPTION
**Pull request by bnevis-i**
Delayed start is not working for support services. Among other problems, for support services,
the service key is support-servicename,
but the service key in docker-compose is just servicename.

Update pre-seeding script to account for this.

Signed-off-by: Bryon Nevis <bryon.nevis@intel.com>

Closes #4152

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?) n/a
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?) n/a
  <link to docs PR>

## Testing Instructions
(Update later with related edgex-compose change.)

### CODE REVIEW

File: cmd/security-spire-config/seed_builtin_entries.sh [hunk 1]
```diff
@@ -26,14 +26,16 @@ echo "SPIFFE_SERVER_SOCKET=${SPIFFE_SERVER_SOCKET}"
...
+for dockerservice in security-spiffe-token-provider support-notifications support-scheduler \
     device-bacnet device-camera device-grove device-modbus device-mqtt device-rest device-snmp \
     device-virtual device-rfid-llrp device-coap device-gpio \
     app-service-http-export app-service-mqtt-export app-service-sample app-rfid-llrp-inventory \
     app-service-external-mqtt-trigger; do
     # Temporary workaround because service name in dockerfile is not consistent with service key.
     # TAF scripts depend on legacy docker-compose service name. Fix in EdgeX 3.0.
-    service=`echo -n ${dockerservice} | sed -e 's/app-service-/app-/'` 
+    service=`echo -n ${dockerservice} | sed -e 's/app-service-/app-/'`
+    # support- services have the opposite problem.  service key is right, service name in docker isn't
```
Comment (lenny-intel) [inline cmd/security-spire-config/seed_builtin_entries.sh:37]: Same issue with the `core services`. Service name is `data` while the service key is `core-data'. Something we need to clean-up in EdgeX 3.0. I have update this issue to cover App, Core and Support service names.
https://github.com/edgexfoundry/edgex-compose/issues/231

**Review by lenny-intel — APPROVED** [review]
LGTM
