### PR TITLE
fix(metadata): not trigger DS callback if only lastConnected is updated

### LINKED ISSUE #3641: Update lastConnected should not trigger the Device Service callback
### Affected Services

 The issue is located in: core-metadata

### Is this a regression?
No

### Description and Minimal Reproduction
When lastConnected timestamp is updated, it also triggers the Device Service callback, which is unnecessary.

### PR DESCRIPTION
**Pull request by hahattan**
fix #3641

Signed-off-by: Chris Hung <chris@iotechsys.com>

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [x] I have added unit tests for the new feature or bug fix (if not, why?)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?) n/a
  <link to docs PR>

## Testing Instructions

1. run metadata from this branch
2. run device-virtual with `DEBUG` log level
3. verify PATCH `/api/v2/deviceprofile` will not trigger DS callback if only updating `lastConnected` field

### CODE REVIEW

File: internal/core/metadata/application/deviceservice.go [hunk 1]
```diff
@@ -77,6 +77,11 @@ func PatchDeviceService(dto dtos.UpdateDeviceService, ctx context.Context, dic *
 		"DeviceService patched on DB successfully. Correlation-ID: %s ",
 		correlation.FromContext(ctx),
 	)
+	// Don't invoke callback if only lastConnected field is updated
+	if dto.LastConnected != nil && dto.Description == nil && dto.LastReported == nil &&
+		dto.BaseAddress == nil && dto.AdminState == nil && len(dto.Labels) == 0 {
```
Comment (cloudxxx8) [inline internal/core/metadata/application/deviceservice.go:82]: It's a good idea to not invoke callback if only lastConnected field is updated.
However, this if statement is hard to maintain if we add more fields into the Device struct.
Please write a helper function and use the reflect package to replace this if statement.
https://pkg.go.dev/reflect
Use a for loop to go through all the fields in this DTO and check the logic you designed.

**Review by cloudxxx8 — CHANGES_REQUESTED** [review]

**Review by cloudxxx8 — APPROVED** [review]
LGTM

**Review by lenny-intel — APPROVED** [review]
LGTM
