### PR TITLE
Fix orphaned event checksum data for Redis

### LINKED ISSUE #2143: Delete event func for Redis misses the deletion of the checksum collection for binary data
# 🐞 Bug Report

### Affected Services
The issue is located in: Core-Data

### Is this a regression?
No, it also happens in Edinburgh release

### Description and Minimal Reproduction
When creating the event, there is an additional collections added to reference to the event id for binary data
https://github.com/edgexfoundry/edgex-go/blob/d7fd3d05ee7535716585419652c1d825b0693da7/internal/pkg/db/redis/data.go#L1060-L1062

However, the deleteEvent func doesn't delete it
https://github.com/edgexfoundry/edgex-go/blob/d7fd3d05ee7535716585419652c1d825b0693da7/internal/pkg/db/redis/data.go#L1091-L1119

## 🔥 Exception or Error
The data will keep growing until out of memory

## 🌍  Your Environment
**Deployment Environment:**
Ubuntu

**EdgeX Version:**
Edinburgh and Fuji

**Anything else relevant?**
it is similar to https://github.com/edgexfoundry/edgex-go/issues/2076

### PR DESCRIPTION
**Pull request by AnthonyMBonafide**
Fix #2143

Update the deleteEvent function to perform an extra lookup for the
checksum value associated with the event to be deleted and remove the
lingering data. The additional lookup is necessary since there are three
different types of Events(correlation,contract,and redisEvent) being
used within the Redis implementation of the DBClient and the one being
used for common lookups(contract) does not have the checksum information
so it is lost during serialization. The approach is the most direct and
non-invasive solution. Other attempts to clean-up and reduce the
divergence of the types being used resulted in unrelated Blackbox test
failures.

Signed-off-by: Anthony M. Bonafide <AnthonyMBonafide@gmail.com>

### CODE REVIEW

**Comment by AnthonyMBonafide** [comment]
This fix will also go into `fuji`, I will cherry-pick this commit once it is approved.

File: internal/pkg/db/redis/data.go [hunk 1]
```diff
@@ -1097,13 +1097,25 @@ func deleteEvent(conn redis.Conn, id string) error {
 		return err
 	}
 
+	// Obtain the checksum associated with the event.
+	// This is necessary since the helper functions result in an Event type which does not contain the checksum
```
Comment (brandonforster) [inline internal/pkg/db/redis/data.go]: Would it be better to modify the helper functions to return a Redis model instead of a contract?

**Comment by AnthonyMBonafide** [comment]
These changes were verified manually by creating, then deleting an event, and ensuring the data was no longer available in Redis. The blackbox tests were also used to confirm these changes. However, the tests are failing when run against `master` using Redis, so the tests are not completely reliable, but I verified these changes result in the same failures as witnessed when executing against master and all other tests pass.

An issue has been created to fix the failures for the blackbox tests: #2163

File: internal/pkg/db/redis/data.go (hunk 1 above)
Comment (AnthonyMBonafide) [reply internal/pkg/db/redis/data.go]: That was my original intent, but that caused other things to break. Rather than digging for a root cause, I went with this direct approach to provide a fix for the bug rather than re-working the whole structure of the Redis DBClient. The problem is that the Redis DBClient is using 3 different representations of the Event type and its not clear which is being used  and we got into this odd situation. Another problem is that the Blackbox tests are not being run, and they seem to not be working so I am very hesitant to start restructuring everything. When I attempted to clean things up the blackbox tests showed even more failures than it is already reporting. I am going to create an issue to go back and re-work the Redis client.

Comment (AnthonyMBonafide) [reply internal/pkg/db/redis/data.go]: Created the issue to clean this up: #2166

**Comment by michaelestrin** [comment]
> tests are failing when run against `master` using Redis, so the tests are not completely reliable

Are the tests "not completely reliable" or are the test failures valid?
