### PR TITLE
Fix issue #2200: retrieve certs for security-proxy-setup with go-mod-bootstrap

### LINKED ISSUE #2200: Convert security-proxy-setup to use go-mod-secrets (dependency tracker fix for master)
# 🐞 Bug Report

### Affected Services
security-proxy-setup

### Description and Minimal Reproduction
Convert security-proxy-setup to use go-mod-secrets in the `Load()` method of internal/security/proxy/certs.go

Required to fix #1710 on master branch.

### PR DESCRIPTION
**Pull request by tingyuz**
This PR is to fix #2200

Using go-mod-bootstrap (through go-mod-secrets) to retrieve ssl certificate pair for proxy

Signed-off-by: Tingyu Zeng <tingyu.zeng@rsa.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://wiki.edgexfoundry.org/display/FA/Contributor%27s+Guide
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?
The security-proxy-setup is creating a HTTP request to retrieve ssl cert pair from security-secretstore (Vault).

Issue Number:
#2200 

## What is the new behavior?
Following similar logic as other core microservices ( such as coredata, metadata etc.), the security-proxy-setup is using go-mod-bootstrap to retrieve ssl cert pair for proxy. 

## Does this PR introduce a breaking change?
- [ ] Yes
- [X] No

## Are there any specific instructions or things that should be known prior to reviewing?
No.
## Other information
To test the change, build edgex-proxy-setup locally, and pull the nightly docker-compose file, then update the image of edgex-proxy to your local build, then run the docker-compose file. Then check the logs of edgex-proxy to make sure the proxy is initialized successfully. If everything works, logs will show "exit 0" at the end.

### CODE REVIEW

File: internal/security/proxy/config/config.go [hunk 1]
```diff
@@ -129,10 +131,26 @@ func (c *ConfigurationStruct) UpdateWritableFromRaw(rawWritable interface{}) boo
...
 // into an interfaces.BootstrapConfiguration struct contained within ConfigurationStruct).
 func (c *ConfigurationStruct) GetBootstrap() interfaces.BootstrapConfiguration {
+	//To keep config file for proxy unchanged in Geneva we need to create a temporary SecretStore struct so that bootstrapHandler can use it to create a secret client
+	//The config file may be changed in the future version and SecretStore can be used directly like other core services
+	ss := bootstrapConfig.SecretStoreInfo{
+		Host:                    c.SecretService.Server,
+		Port:                    c.SecretService.Port,
+		Path:                    c.SecretService.CertPath,
+		Protocol:                "https",
+		RootCaCertPath:          c.SecretService.CACertPath,
```
Comment (jim-wang-intel) [inline internal/security/proxy/config/config.go]: Suggest to having input validation on the required configuration items; eg. the path should not be empty and should be well-formed because now the Protocol is https for sure.

File: internal/security/proxy/config/config.go [hunk 2]
```diff
@@ -129,10 +131,26 @@ func (c *ConfigurationStruct) UpdateWritableFromRaw(rawWritable interface{}) boo
...
+		ServerName:              c.SecretService.Server,
+		Authentication:          vault.AuthenticationInfo{AuthType: "X-Vault-Token"},
```
Comment (jim-wang-intel) [inline internal/security/proxy/config/config.go]: could use a constant for `X-Vault-Token`

File: cmd/security-proxy-setup/res/docker/configuration.toml [hunk 3]
```diff
@@ -45,7 +45,7 @@ WhiteList = "admin"
 Server = "edgex-vault"
 Port = 8200
 HealthCheckPath = "v1/sys/health"
-CertPath = "v1/secret/edgex/edgex-security-proxy-setup/kong-tls"
+CertPath = "/v1/secret/edgex/edgex-security-proxy-setup/"
```
Comment (tsconn23) [inline cmd/security-proxy-setup/res/docker/configuration.toml]: This looks to me like a backward incompatible change based on the recent discussions in Core WG about pathing in configuration. I assume such restrictions would apply to Vault paths as well. Thoughts @lenny-intel ?

File: internal/security/proxy/config/config.go [hunk 4]
```diff
@@ -129,10 +131,26 @@ func (c *ConfigurationStruct) UpdateWritableFromRaw(rawWritable interface{}) boo
...
+		AdditionalRetryAttempts: 10,
+		RetryWaitPeriod:         "5s",
+		TokenFile:               c.SecretService.TokenPath,
```
Comment (jim-wang-intel) [inline internal/security/proxy/config/config.go]: input validation?

File: cmd/security-proxy-setup/res/docker/configuration.toml (hunk 3 above)
Comment (lenny-intel) [reply cmd/security-proxy-setup/res/docker/configuration.toml]: @tsconn23 Not sure that a change in the value is a breaking change. Also this is specific to this service which we deliver,  not a module or SDK. IMO, I think it is OK.

File: internal/security/proxy/config/config.go (hunk 1 above)
Comment (tingyuz) [reply internal/security/proxy/config/config.go]: Mark this resolved per Bryon's comments.

File: internal/security/proxy/config/config.go (hunk 4 above)
Comment (tingyuz) [reply internal/security/proxy/config/config.go]: Mark this resolved per Bryon's comments.
