### PR TITLE
Fix Redis Readings By Device & Value Descriptor

### LINKED ISSUE #2344: Fail to query readings from RedisDB by value descriptor name and device name
# 🐞 Bug Report

### Affected Services

 The issue is located in: core-data

### Is this a regression?

 No

### Description and Minimal Reproduction
1.  Run core-data to use Redis
2. Add readings:
```
curl -H 'Content-Type: application/json' http://localhost:48080/api/v1/reading -d '{"device":"testDevice","name":"val1","value":"10"}'

curl -H 'Content-Type: application/json' http://localhost:48080/api/v1/reading -d '{"device":"testDevice","name":"val2","value":"20"}'
```

3. Query reading by value descriptor name and device name and the error occur at second http request:
```
curl http://localhost:48080/api/v1/reading/name/val1/device/testDevice/1 
[{"id":"191d2c04-db0c-4df2-a89a-3a2fff1c0698","created":1581064189094,"device":"testDevice","name":"val1","value":"10"}]

curl http://localhost:48080/api/v1/reading/name/val2/device/testDevice/1
ERR wrong number of arguments for 'mget' command
```

## 🔥 Exception or Error
<pre><code>
curl http://localhost:48080/api/v1/reading/name/val2/device/testDevice/1
ERR wrong number of arguments for 'mget' command
</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version:**
Master branch

### PR DESCRIPTION
**Pull request by AnthonyMBonafide**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://wiki.edgexfoundry.org/display/FA/Contributor%27s+Guide
- [ ] Tests for the changes have been added (for bug fixes / features) **N/A No Blackbox tests for Redis**
- [ ] Docs have been added / updated (for bug fixes / features) **N/A**

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?
Requests to obtain readings based on device name and value descriptor does not return the correct data when there are multiple readings associated with a device. Please see issue for more details.
 
Issue Number: #2344

## What is the new behavior?
Requests return the correct data when there are multiple readings for a device

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Are there any specific instructions or things that should be known prior to reviewing?
I updated `getObjectsByValuesSorted` to get around some out of bounds(OOB) indexing issues I ran into during some manual verification. I experienced the OOB issues when providing a `limit` which was larger than the amount of readings. For example, with the setup mentioned in the associated issue, if you use a limit of `3` you will notice panic statements in the service's logs.

Ensure you are verifying these changes with Redis, by default the blackbox tests do not test against Redis and requires some additional setup and adjustments.

## Other information
I verified these changes with passing unit tests, passing blackbox tests, and manually executed the commands presented in the original issue as well as varying limits and number of readings associated with the same device name.

### CODE REVIEW

**Comment by AnthonyMBonafide** [comment]
Thank you @weichou1229 for the proposal in the original issue. I was not aware of the `ZINTERSTORE` function in within Redis. Your comment helped a lot.

File: internal/pkg/db/redis/queries.go [hunk 1]
```diff
@@ -291,7 +291,7 @@ func getObjectsByValuesSorted(conn redis.Conn, limit int, vals ...string) (objec
 		return nil, err
 	}
```
Comment (weichou1229) [inline internal/pkg/db/redis/queries.go]: Here should check the len(ids) ==0 to prevent the same error `ERR wrong number of arguments for 'mget' command`
```	
	if len(ids) ==0 {
		return objects ,nil
	}
```

**Comment by michaelestrin** [comment]
@andresrinivasan are you able to review?

**Comment by michaelestrin** [comment]
https://github.com/edgexfoundry/edgex-go/issues/2374
