### PR TITLE
[FUJI BRANCH] Fix nil panic when configuration.toml can't be loaded.

### LINKED ISSUE #1814: panic running security-secretstore-setup and security-proxy-setup
# 🐞 Bug Report

Running security-secretstore-setup with res/configuration.toml missing causes a panic due to undefined LoggingClient.

See:

```
./security-secretstore-setup --init=true
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x8a5ae4]

goroutine 17 [running]:
github.com/edgexfoundry/edgex-go/internal/pkg/config.LoadFromFile(0x0, 0x0, 0x0, 0x0, 0x8e1480, 0xc0000b3d40, 0x5d8a5505, 0xc0223daddb)
        /home/ijohnson/git/edgex/edgex-go/internal/pkg/config/loader.go:52 +0x214
github.com/edgexfoundry/edgex-go/internal/security/secretstore.initializeConfiguration(0xbf5ab321623dad00, 0x0, 0x0, 0x0, 0x0, 0xe47d20, 0xe47d01, 0x1)
        /home/ijohnson/git/edgex/edgex-go/internal/security/secretstore/init.go:68 +0x78
github.com/edgexfoundry/edgex-go/internal/security/secretstore.Retry(0xc000140100, 0x0, 0x0, 0x0, 0x0, 0x7530, 0xc00013c050, 0xc0001401e0)
        /home/ijohnson/git/edgex/edgex-go/internal/security/secretstore/init.go:37 +0x131
created by github.com/edgexfoundry/edgex-go/internal/pkg/startup.Bootstrap
        /home/ijohnson/git/edgex/edgex-go/internal/pkg/startup/bootstrap.go:37 +0xe4
```

This is because the LoggingClient in LoadFromFile is nil because we haven't been able to load the configuration file at this point in time yet.

### Affected Services

The issue is located in: security-secretstore-setup

### Is this a regression?

Maybe...

This was from master @ abc9af1de59ab5c4130efe3914aaf2c6688b4e14

### PR DESCRIPTION
**Pull request by bnevis-i**
Fix nil panic when configuration.toml can't be loaded.

Fixes #1814 

When configuration.toml can't be loaded, the
LoggingClient global variable isn't initialized,
causing main program to panic when it attempts
to log that configuration.toml can't be loaded.

This is a temporary workaround until security-proxy-setup
is migrated to the common bootstrap.

Signed-off-by: Bryon Nevis <bryon.nevis@intel.com>

### CODE REVIEW

File: cmd/security-proxy-setup/main.go [hunk 1]
```diff
@@ -64,6 +64,10 @@ func main() {
 		BootTimeout: internal.BootTimeoutDefault,
 	}
 	startup.Bootstrap(params, proxy.Retry, logBeforeInit)
+	if proxy.Configuration == nil {
+		// proxy.LoggingClient wasn't initialized either
+		os.Exit(1)
```
Comment (jim-wang-intel) [inline cmd/security-proxy-setup/main.go]: Before exit out- add some fmt print out for troubleshooting.

**Comment by bnevis-i** [comment]
Assign to @tingyuz.  Feel free to merge if you want it in Fuji, else close.

**Comment by anonymouse64** [comment]
I think it's fine to pull this into Fuji, but I would like to land #2052 first so that I am unblocked on fully testing #2053 (but obviously we can land this before 2053)

**Comment by anonymouse64** [comment]
This can go in now, thanks for your patience

**Comment by anonymouse64** [comment]
Note that you will need to rebase, even though GitHub says it's not out of date for some reason

**Comment by bnevis-i** [comment]
Interesting observation.  Rebased.

File: cmd/security-proxy-setup/main.go (hunk 1 above)
Comment (bnevis-i) [reply cmd/security-proxy-setup/main.go]: Here is what actually happens:
```
../security-proxy-setup --init=true
level=ERROR ts=2019-11-01T18:10:16.2489911Z app=edgex-security-proxy-setup source=logger.go:73 msg="logTarget cannot be blank, using stdout only"
level=ERROR ts=2019-11-01T18:10:16.249481831Z app=edgex-security-proxy-setup source=loader.go:52 msg="could not load configuration file (./res/configuration.toml): open ./res/configuration.toml: no such file or directory"
```
