### PR TITLE
Fixed incorrect errorConcepts applied to Core Data

### LINKED ISSUE #1901: Incorrect return code when running negative reading/valuedescriptor test cases
# 🐞 Bug Report

### Affected Services

 The issue is located in: Data

### Is this a regression? Yes

 Yes, the previous version in which this bug was not present was: ....

### Description and Minimal Reproduction
API : {{baseURL}}:48080/api/v1/reading
Method : PUT
Request body: 
```
{
    "id": "57e866d4e4b0ca8e6d73a412",
    "created": 1475227070170,
    "modified": 1475227070170,
    "origin": 1471806366619,
    "device": "powerScoutMeter",
    "pushed": 0,
    "name": "co2",
    "value": "12"
}
```
**Expected return code : 404
Actual return code : 500**

The following test cases also failed and returned "500 Internal Server Error" on the BlackBox test.

- reading_error_4xx / 38 http://localhost:48080/api/v1/reading
- reading_error_4xx / 47 http://localhost:48080/api/v1/reading/id/:id
- valuedescriptor_error_4xx / 103 http://localhost:48080/api/v1/valuedescriptor
- valuedescriptor_error_4xx / 72 http://localhost:48080/api/v1/valuedescriptor
- valuedescriptor_error_4xx / 77 http://localhost:48080/api/v1/valuedescriptor/id/:id
- valuedescriptor_error_4xx / 78 http://localhost:48080/api/v1/valuedescriptor/id/:id 409
- valuedescriptor_error_4xx / 83 http://localhost:48080/api/v1/valuedescriptor/name/:name
- valuedescriptor_error_4xx / 84 http://localhost:48080/api/v1/valuedescriptor/name/:name 409

## 🔥 Exception or Error
<pre><code> Got return code : 500 Internal Server Error

</code></pre>

## 🌍  Your Environment
**Deployment Environment:** Ubuntu 18.04

**EdgeX Version:** Master

**Anything else relevant?**

### LINKED ISSUE #1909: core-data REST Handlers errorconcept.Database.NotFound usage
Code merged in #1877 for issue #1860 is using errorconcept.Database.NotFound to replace type switch on errors.ErrDbNotFound.  They are not compatible -- former checks an error value, not a type.  Some blackbox tests fail.

Note also additional correction to same issue/PR in https://github.com/edgexfoundry/edgex-go/pull/1908.

### PR DESCRIPTION
**Pull request by brandonforster**
Fixes #1909.
Fixes #1901.

Addresses several more issues of this type in the file. 

Blackbox test 69 in valuedescriptor_error is still failing; I believe this is unrelated and an underlying issue in the code.

Signed-off-by: Brandon Forster <brandonforster@gmail.com>

### CODE REVIEW

**Comment by michaelestrin** [comment]
@jbonafide623 -- please do an initial review.  Comment but do not approve.

**Comment by brandonforster** [comment]
@cherrycl Please verify that this addresses the blackbox failures.

**Comment by tsconn23** [comment]
@brandonforster The value descriptor tests referenced in #1901 are still failing
Screen Shot 2019-10-15 at 7 46 37 PM

**Comment by michaelestrin** [comment]
I get a slightly different set of failures when I execute the tests against the master branch immediately prior to merge of #1860 (529ef6277e707da6113a3c7bd2785904cbdc2cb4):

```
 1.  AssertionError  Status code is 404                                                                                   
                     expected false to be truthy                                                                          
                     at assertion:0 in test-script                                                                        
                     inside "valuedescriptor_error_4xx / 77 http://localhost:48080/api/v1/valuedescriptor/id/:id"         
                                                                                                                          
 2.  AssertionError  Status code is 409                                                                                   
                     expected false to be truthy                                                                          
                     at assertion:0 in test-script                                                                        
                     inside "valuedescriptor_error_4xx / 84 http://localhost:48080/api/v1/valuedescriptor/name/:name 409" 
                                                                                                                          
 3.  AssertionError  Status code is 409                                                                                   
                     expected false to be truthy                                                                          
                     at assertion:0 in test-script                                                                        
                     inside "valuedescriptor_error_4xx / 103 http://localhost:48080/api/v1/valuedescriptor"    
```
Corresponding core-data logging for the test run:

```
level=ERROR ts=2019-10-16T14:28:29.4719613Z app=edgex-core-data source=valuedescriptor.go:74 msg="Item not found"
level=ERROR ts=2019-10-16T14:28:29.5307313Z app=edgex-core-data source=valuedescriptor.go:211 msg="Resource already exists"
level=ERROR ts=2019-10-16T14:28:29.5760888Z app=edgex-core-data source=valuedescriptor.go:74 msg="Invalid object ID"
level=ERROR ts=2019-10-16T14:28:29.6200505Z app=edgex-core-data source=valuedescriptor.go:59 msg="Item not found"
level=ERROR ts=2019-10-16T14:28:29.6737845Z app=edgex-core-data source=valuedescriptor.go:306 msg="Data integrity issue.  Value Descriptor is still referenced by existing readings."
level=ERROR ts=2019-10-16T14:28:29.7175067Z app=edgex-core-data source=valuedescriptor.go:59 msg="Item not found"
level=ERROR ts=2019-10-16T14:28:29.7732404Z app=edgex-core-data source=utils.go:37 msg="Error, exceeded the max limit as defined in config"
level=ERROR ts=2019-10-16T14:28:29.7742473Z app=edgex-core-data source=valuedescriptor.go:262 msg="Error checking the readings for the value descriptor: limit 10 exceeds configured max"
level=ERROR ts=2019-10-16T14:28:29.8087197Z app=edgex-core-data source=valuedescriptor.go:211 msg="Resource already exists"
```

**Comment by brandonforster** [comment]
@tsconn23 @michaelestrin @cherrycl Thank you for your feedback, I missed the error `ValueDescriptorInUse`; I had `ValueDescriptorsInUse`

File: internal/core/data/router.go [hunk 1]
```diff
@@ -1106,7 +1106,7 @@ func valueDescriptorHandler(w http.ResponseWriter, r *http.Request) {
 				w,
 				err,
 				[]errorconcept.ErrorConceptType{
-					errorconcept.Common.JsonDecoding,
+					errorconcept.CoreData.JsonDecoding,
```
Comment (jbonafide623) [inline internal/core/data/router.go]: Any reason why errorConept.Common.JsonDecoding can't be used here?

This comment ties into my comment in coredata.go

File: internal/pkg/errorconcept/coredata.go [hunk 2]
```diff
@@ -0,0 +1,59 @@
...
+
+var CoreData coreDataErrorConcept
+
+// coreDataErrorConcept contains the superfluous, duplicated errors that must be handled for CoreData
+type coreDataErrorConcept struct {
+	DBNotFound   coreDataDBNotFound
+	JsonDecoding coreDataJSONDecoding
+}
+
+type coreDataDBNotFound struct{}
```
Comment (jbonafide623) [inline internal/pkg/errorconcept/coredata.go]: Would it make more sense for DBNotfound to reside in db.go and for JsonDecoding to reside in common.go?
I am thinking that this file can lead one to believe that error concepts are split up by service when they are split out by resource.

What are your thoughts?

**Comment by brandonforster** [comment]
recheck

**Comment by tsconn23** [comment]
recheck

**Comment by tsconn23** [comment]
@cherrycl Thanks for the verification

File: internal/pkg/errorconcept/db.go [hunk 3]
```diff
@@ -36,7 +37,12 @@ func (r dbNotFound) httpErrorCode() int {
 }
 
 func (r dbNotFound) isA(err error) bool {
-	return err == db.ErrNotFound
+	if err == db.ErrNotFound {
+		return true
+	} else {
```
Comment (jbonafide623) [inline internal/pkg/errorconcept/db.go]: This else block may be best split out into its own ErrorConceptType. With the addition of the else block, each place which performs error-type-checking via string, will include this extra cycle. There were no scenarios that stood out to me to suggest that this may break anything, however, I think its best to split this out into its own ErrorConceptType and err of the side of caution.

As a side note, the pattern that is in place will help spotlight error-handling inconsistencies throughout edgex-go. This case here is a good example of that. With it defined as its own ErrorConceptType, it helps easily identify the different DBNotFound errors that we check (those which are operator bound and those which are not).

After splitting the err.(data.ErrDbNotFound) type out, I will approve.

**Comment by brandonforster** [comment]
@jbonafide623 @tsconn23 Rebased
