### PR TITLE
fix(snap): deploy secrets token into separate mount points

### LINKED ISSUE #3827: Unable to install edgexfoundry after device/app snaps
The new deferred startup feature added by #3813 changes the stage in which tokens get generated from the install to the configure hook. As a result, tokens are not always available when the connect hook for `edgex-secretstore-token` is called.

This happens only when a consumer (device/app) snap is installed before edgexfoundry snap, only if both are from the same publisher and installed from the store. In other words, the installation fails only when `edgex-secretstore-token` is auto-connected as part of edgexfoundry snap installation.

# 🐞 Bug Report

### Affected Services
1st party device or app services in combination with the edgex-go.

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 2.0.0

## 🔥 Exception or Error
First, remove the snaps:
```
$ sudo snap remove edgex-device-camera edgexfoundry
```

Then:
```
$ sudo snap install edgex-device-camera --channel=2.1/beta
edgex-device-camera (edge) 2.1.0 from Canonical✓ installed
$ sudo snap install edgexfoundry --channel=2.1/beta
error: cannot perform the following tasks:
- Run hook prepare-plug-edgex-secretstore-token of snap "edgexfoundry" (run hook "prepare-plug-edgex-secretstore-token": <13>Nov 25 10:49:07 root: edgex-secretstore-token: could not find token for device-camera)
```

## 🌍  Your Environment
**Deployment Environment:**
Snap

**EdgeX Version:**
2.1.0 (beta)

**Anything else relevant?**

### PR DESCRIPTION
**Pull request by farshidtz**
This change is mostly a refactoring to make the edgex-secretstore-tokens interface connection compatible with the deferred startup feature: https://github.com/edgexfoundry/edgex-go/pull/3813. But since the change is already releases and led to an issue, I would call this a fix.

Fixes #3827

Signed-off-by: Farshid Tavakolizadeh <farshid.tavakolizadeh@canonical.com>

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

#### Install from the branched release to test the auto-connection (device snap before):
```
# remove snaps
$ sudo snap remove edgex-device-camera edgexfoundry

# install device-camera
$ sudo snap install edgex-device-camera --edge
edgex-device-camera (edge) 2.1.0 from Canonical✓ installed

# install edgexfoundy from the branch
$ sudo snap install edgexfoundry --channel=edge/secrets-connect-fix
edgexfoundry (edge/secrets-connect-fix) 2.2.0-dev.1 from Canonical✓ installed

# check the connection, it should be connected automatically:
$ sudo snap connections edgexfoundry
Interface                         Plug                                  Slot                                         Notes
content[edgex-secretstore-token]  edgexfoundry:edgex-secretstore-token  edgex-device-camera:edgex-secretstore-token  -

# ensure that token is copied
$ sudo ls /var/snap/edgex-device-camera/current/device-camera/secrets-token.json
/var/snap/edgex-device-camera/current/device-camera/secrets-token.json
```

Optional (remove, disconnect, re-connect):
```
$ sudo rm /var/snap/edgex-device-camera/current/device-camera/secrets-token.json
$ sudo snap disconnect edgexfoundry:edgex-secretstore-token edgex-device-camera:edgex-secretstore-token
$ sudo snap connect edgexfoundry:edgex-secretstore-token edgex-device-camera:edgex-secretstore-token
$ sudo ls /var/snap/edgex-device-camera/current/device-camera/secrets-token.json
/var/snap/edgex-device-camera/current/device-camera/secrets-token.json
```

#### Install from the branched release to test the auto-connection (device snap after):
```
# remove snaps
$ sudo snap remove edgex-device-camera edgexfoundry

# install edgexfoundy from the branch
$ sudo snap install edgexfoundry --channel=edge/secrets-connect-fix
edgexfoundry (edge/secrets-connect-fix) 2.2.0-dev.1 from Canonical✓ installed

# install device-camera
$ sudo snap install edgex-device-camera --edge
edgex-device-camera (edge) 2.1.0 from Canonical✓ installed

# ensure that token is copied
$ sudo ls /var/snap/edgex-device-camera/current/device-camera/secrets-token.json
/var/snap/edgex-device-camera/current/device-camera/secrets-token.json
```

#### Using a locally-build edgexfoundry.  In this case the plug doesn't connect automatically:
```
# remove snaps
$ sudo snap remove edgex-device-camera edgexfoundry

# assuming you've already built the snap from this branch, install:
$ sudo snap install edgexfoundry_2.2.0-dev.1_amd64.snap --dangerous
edgexfoundry 2.2.0-dev.1 installed

# install device-camera
$ sudo snap install edgex-device-camera --edge
edgex-device-camera (edge) 2.1.0 from Canonical✓ installed

# connect the plug
$ sudo snap connect edgexfoundry:edgex-secretstore-token edgex-device-camera:edgex-secretstore-token

# ensure that token is copied
$ sudo ls /var/snap/edgex-device-camera/current/device-camera/secrets-token.json
/var/snap/edgex-device-camera/current/device-camera/secrets-token.json
```

### CODE REVIEW

File: snap/hooks/prepare-plug-edgex-secretstore-token [hunk 1]
```diff
@@ -1,48 +1,8 @@
 #!/bin/bash
 
-# This connection can happen before or after security-secretstore-setup
-# (a oneshot service that configures Vault) has already run. The first
-# case happens when the content interface is auto-connected and the
-# external snap is installed before the edgexfoundry
-# snap. In this case there's no action required as security-secretstore-
-# -setup will write it's token to the source dir which has been bind
-# mounted over the dir of the same name in this snap.
+# This script needs to exist, for an unknown reason to avoid the following error:
```
Comment (siggiskulason) [inline snap/hooks/prepare-plug-edgex-secretstore-token:3]: @anonymouse64 - could you comment on why not including this empty script causes this error?

**Review by siggiskulason — APPROVED** [review]
Excellent. Everything works as expected. Thanks for uploading the snap to the branch, which made testing easier. I like the idea of using the post-stop-command.

File: snap/hooks/prepare-plug-edgex-secretstore-token [hunk 2]
```diff
@@ -1,48 +1,8 @@
...
-        cp "$APP_SVC_TOKEN" "$TARGET_PATH"
-    else
-        logger --stderr "edgex-secretstore-token: could not find token for $filename"
-        exit 1
-    fi
-done
+# Run hook prepare-plug-edgex-secretstore-token of snap "edgexfoundry" (run hook
+# "prepare-plug-edgex-secretstore-token": 
+# /snap/edgexfoundry/3358/snap/command-chain/snapcraft-runner: 6: exec: 
+# /snap/edgexfoundry/3358/meta/hooks/prepare-plug-edgex-secretstore-token: not found)
```
Comment (anonymouse64) [inline snap/hooks/prepare-plug-edgex-secretstore-token]: this is because we declare the hook in the snapcraft.yaml, see:

https://github.com/edgexfoundry/edgex-go/blob/b7985a5e213d1adc6c93ffba227765f14366fda1/snap/snapcraft.yaml#L61-L66

I don't know if these interface hooks are still needed or not though

File: snap/hooks/prepare-plug-edgex-secretstore-token (hunk 1 above)
Comment (anonymouse64) [reply snap/hooks/prepare-plug-edgex-secretstore-token]: sorry meant the other comment to be a reply, see this: https://github.com/edgexfoundry/edgex-go/pull/3826/files/3b0cf43c7e43d1d5d2a17e9468597ccdf90f6ff1#r759344916

File: snap/hooks/prepare-plug-edgex-secretstore-token (hunk 2 above)
Comment (farshidtz) [reply snap/hooks/prepare-plug-edgex-secretstore-token]: Thanks. Removing it from `passthrough.hooks` solves it. I've now removed the script as well.

**Review by tonyespy — DISMISSED** [review]
Overall this looks OK to me, although I still think it would've been possible to adjust the original implementation...  I ran through all of your test scenarios other then the side-loading scenario and everything works as expected.

FYI, you do need to rebase on latest.

File: snap/local/runtime-helpers/bin/security-secretstore-post-setup.sh [hunk 3]
```diff
@@ -0,0 +1,51 @@
...
+# respective hook script.
+
+# The caller is either post-stop-command from snapcraft.yaml (default)
+# or the connect-plug-edgex-secretstore-token hook
+caller=${1:-"post-stop-command"}
+
+logger "edgex-secretstore:post-setup: started by $caller"
+
+# create the directory which consumers bind-mount into
+mkdir -p $SNAP_DATA/mount/secrets
```
[the remark this answers is not in the document]
Comment (farshidtz) [reply snap/local/runtime-helpers/bin/security-secretstore-post-setup.sh:17]: That makes sense, but because it is tightly coupled to this "setup" script, I prefer to leave it here for clarity.

File: snap/local/runtime-helpers/bin/security-secretstore-post-setup.sh [hunk 4]
```diff
@@ -0,0 +1,51 @@
...
+
+# each directory corresponds to one service
```
[the remark this answers is not in the document]
Comment (farshidtz) [reply snap/local/runtime-helpers/bin/security-secretstore-post-setup.sh]: Thanks, added.

**Comment by farshidtz** [comment]
Thanks a lot @siggiskulason and @tonyespy for your reviews. 

This is now ready to be merged. Please press "Update branch" button right before merging, I'd rather not chase after the main.

Please squash and merging.

**Review by siggiskulason — APPROVED** [review]
LGTM.
