### PR TITLE
fix: Add warn log for create/update interval

### LINKED ISSUE #4586: CPU increases abnormal when creating interval with us/ns unit
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: support-scheduler

### Is this a regression?

 No

### Description and Minimal Reproduction [**REQUIRED**]
1. Deploy EdgeX
2. Create interval with us/ns
```
POST http://localhost:59861/api/v3/interval
[
   {
      "interval":{
         "name":"interval_1679737508110",
         "start":"20230605T094508",
         "interval":"1us"
      },
      "apiVersion":"v3"
   }
]
```

## 🔥 Exception or Error
<pre><code>
Status code: 503
Response body: HTTP request timeout
CPU: more than 200% (view CPU by "docker stats")

</code></pre>

## 🌍  Your Environment
**Deployment Environment:** Ubuntu 22.04 / x86

**EdgeX Version [**REQUIRED**]:** Main

**Anything else relevant?**

### PR DESCRIPTION
**Pull request by lindseysimple**
Add warn log for interval value from Interval and AutoEvent if the value is less than the suggested value.

Closes #4586.

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [x] I have added unit tests for the new feature or bug fix (if not, why?)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?) - _no doc change needed as the change only shows the warning logs when the interval value is less than the suggested value._
  <link to docs PR>

## Testing Instructions

Invoke the POST interval API with the following command:
```
curl --location 'http://localhost:59861/api/v3/interval' \
--header 'Content-Type: application/json' \
--data '  [ 
    {
      "apiVersion":"v3",
      "interval":{
         "name":"test",
         "start":"20230707T094508",
         "interval":"599us"
      }
   }
  ]'
```
The following warning log should be displayed in the support-scheduler log:
```
level=WARN ts=2023-07-05T07:27:29.922821Z app=support-scheduler source=time.go:30 msg="the interval value '599µs' is smaller than the suggested value '10ms', which might cause abnormal CPU increase"
```

### CODE REVIEW

**Review by cloudxxx8 — APPROVED** [review]
LGTM

File: internal/pkg/utils/time.go [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+
+import (
+	"time"
+
+	"github.com/edgexfoundry/go-mod-core-contracts/v3/clients/logger"
+)
+
+// CheckMinInterval parses the ISO 8601 time duration string to Duration type
+// and evaluates if the duration value is smaller than the suggested minimum duration string
+func CheckMinInterval(value string, min string, lc logger.LoggingClient) bool {
```
Comment (lenny-intel) [inline internal/pkg/utils/time.go:16]: Pass min as time.Durationand instead of string so it doesn't need to be parsed.

File: internal/support/scheduler/application/interval.go [hunk 2]
```diff
@@ -22,6 +23,9 @@ import (
 	"github.com/edgexfoundry/go-mod-core-contracts/v3/models"
 )
 
+// the suggested minimum duration string for scheduler interval
+const minSchedulerInterval = "10ms"
```
Comment (lenny-intel) [inline internal/support/scheduler/application/interval.go:27]:
```suggestion
const minSchedulerInterval = 10 * time.Milliseconds
```

File: internal/core/metadata/application/device.go [hunk 3]
```diff
@@ -31,8 +31,12 @@ import (
 	"github.com/edgexfoundry/edgex-go/internal/core/metadata/container"
 	"github.com/edgexfoundry/edgex-go/internal/core/metadata/infrastructure/interfaces"
 	"github.com/edgexfoundry/edgex-go/internal/pkg/correlation"
+	"github.com/edgexfoundry/edgex-go/internal/pkg/utils"
 )
 
+// the suggested minimum duration string for auto event interval
+const minAutoEventInterval = "1ms"
```
Comment (lenny-intel) [inline internal/core/metadata/application/device.go:38]:
```suggestion
const minAutoEventInterval = 1 * time.Milliseconds
```

**Review by lenny-intel — CHANGES_REQUESTED** [review]

File: internal/pkg/utils/time.go (hunk 1 above)
Comment (lindseysimple) [reply internal/pkg/utils/time.go]: Done

File: internal/support/scheduler/application/interval.go (hunk 2 above)
Comment (lindseysimple) [reply internal/support/scheduler/application/interval.go]: Done

File: internal/core/metadata/application/device.go (hunk 3 above)
Comment (lindseysimple) [reply internal/core/metadata/application/device.go]: Done

File: internal/pkg/utils/time.go [hunk 4]
```diff
@@ -0,0 +1,29 @@
...
+
+import (
+	"time"
+
+	"github.com/edgexfoundry/go-mod-core-contracts/v3/clients/logger"
+)
+
+// CheckMinInterval parses the ISO 8601 time duration string to Duration type
+// and evaluates if the duration value is smaller than the suggested minimum duration
+func CheckMinInterval(value string, minDuration time.Duration, lc logger.LoggingClient) bool {
```
Comment (lenny-intel) [inline internal/pkg/utils/time.go:16]: Remove return value since it is never used by callers

File: internal/pkg/utils/time_test.go [hunk 5]
```diff
@@ -0,0 +1,36 @@
...
+	"testing"
+	"time"
+
+	"github.com/edgexfoundry/go-mod-core-contracts/v3/clients/logger"
+
+	"github.com/stretchr/testify/assert"
+)
+
+func TestCheckMinInterval(t *testing.T) {
+	lc := logger.NewMockClient()
```
Comment (lenny-intel) [inline internal/pkg/utils/time_test.go:18]: Use mocks.LoggerClient{} and mock.On("Warnf"...) and mock.AssertCalled/AssertNotCalled to test if warning was logged appropriately or not.

**Review by lenny-intel — CHANGES_REQUESTED** [review]

**Comment by lindseysimple** [comment]
recheck

File: internal/pkg/utils/time.go (hunk 4 above)
Comment (lindseysimple) [reply internal/pkg/utils/time.go]: Done

File: internal/pkg/utils/time_test.go (hunk 5 above)
Comment (lindseysimple) [reply internal/pkg/utils/time_test.go]: This suggestion is helpful to verify the logging client method being called, thanks.

**Review by lenny-intel — APPROVED** [review]
LGTM
