### PR TITLE
Remove duplicate "internal" constants for service keys 

### LINKED ISSUE #1345: Code Cleanup: Remove duplicate constants in internal for service keys
In go-mod-core-contracts we have available the following constants (https://github.com/edgexfoundry/go-mod-core-contracts/blob/master/clients/constants.go):
```
const (
	ServiceKeyPrefix                = "edgex-"
	ConfigSeedServiceKey            = "edgex-config-seed"
	CoreCommandServiceKey           = "edgex-core-command"
	CoreDataServiceKey              = "edgex-core-data"
	CoreMetaDataServiceKey          = "edgex-core-metadata"
	ExportClientServiceKey          = "edgex-export-client"
	ExportDistroServiceKey          = "edgex-export-distro"
	SupportLoggingServiceKey        = "edgex-support-logging"
	SupportNotificationsServiceKey  = "edgex-support-notifications"
	SystemManagementAgentServiceKey = "edgex-sys-mgmt-agent"
	SupportSchedulerServiceKey      = "edgex-support-scheduler"
)
```
which happen to also be in located in https://github.com/edgexfoundry/edgex-go/blob/master/internal/constants.go. The exception is the WriteableKey as it is not in go-mod-core-contracts, but potentially could be moved over as it seems relevant and could be used for other services as well. 

Probably a good idea to remove the duplicate code and leverage the go-mod-core-contracts module.

### PR DESCRIPTION
**Pull request by rsdmike**
Fix #1345 

In go-mod-core-contracts we have available the following constants (https://github.com/edgexfoundry/go-mod-core-contracts/blob/master/clients/constants.go): 
```
const (
	ServiceKeyPrefix                = "edgex-"
	ConfigSeedServiceKey            = "edgex-config-seed"
	CoreCommandServiceKey           = "edgex-core-command"
	CoreDataServiceKey              = "edgex-core-data"
	CoreMetaDataServiceKey          = "edgex-core-metadata"
	ExportClientServiceKey          = "edgex-export-client"
	ExportDistroServiceKey          = "edgex-export-distro"
	SupportLoggingServiceKey        = "edgex-support-logging"
	SupportNotificationsServiceKey  = "edgex-support-notifications"
	SystemManagementAgentServiceKey = "edgex-sys-mgmt-agent"
	SupportSchedulerServiceKey      = "edgex-support-scheduler"
)
```
which happen to also be in located in https://github.com/edgexfoundry/edgex-go/blob/master/internal/constants.go. The exception is the `WriteableKey` which for now I have left in internal as it is not in go-mod-core-contracts, but potentially could be moved over as it seems relevant and could be used for other services as well.

With the intention of removing duplicate code, this pull request removes the duplicate "internal" constants for service keys and leverage go-mod-core-contracts throughout edgex-go. This pull request does not depend on any others and is purely a code clean up thing. Noticed it as I was adding the client info sections to the app-functions-sdk.

Signed-off-by: Mike Johanson <michael.johanson@intel.com>

### CODE REVIEW

**Comment by tsconn23** [comment]
@rsdmike Thanks for the work. In the future please associate all PRs to an issue. I know this was an ad hoc thing but create the issue first.

**Comment by rsdmike** [comment]
Will do!

File: internal/seed/config/populate.go [hunk 1]
```diff
@@ -23,6 +23,8 @@ import (
 	"strconv"
 	"strings"
 
+	"github.com/edgexfoundry/go-mod-core-contracts/clients"
```
Comment (lenny-intel) [inline internal/seed/config/populate.go]: Organize imports. This one should be in block below.

File: internal/support/scheduler/init.go [hunk 2]
```diff
@@ -17,13 +17,14 @@ package scheduler
...
 	"errors"
 	"fmt"
-	"github.com/edgexfoundry/edgex-go/internal/pkg/db/redis"
 	"os"
 	"os/signal"
 	"sync"
 	"syscall"
 	"time"
 
+	"github.com/edgexfoundry/edgex-go/internal/pkg/db/redis"
```
Comment (lenny-intel) [inline internal/support/scheduler/init.go]: Organize imports. This one should be in then "internal" block below.

**Comment by tsconn23** [comment]
@rsdmike This looks good. Please make the updates to the `go.mod` we discussed yesterday. Update the ref to `go-mod-core-contracts` and also please update the following:
```
github.com/ugorji/go v1.1.4
```
Once that's done, let me know and we'll merge.
